#!/usr/bin/env bash
#=============================================================================#
# 	htw0056's Bash Profile
#  	Author: htw0056 (huangtw1995@outlook.com)
#=============================================================================#


#=============================================================================#
# Bash                                                                        #
#—————————————————————————————————————————————————————————————————————————————#

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
[[ -f ~/.bash_inc/env ]] && . ~/.bash_inc/env

